config/routes.rb
Rails.application.routes.draw do
  
  resources :groups do
   get "delete"
  end
  resources :students do
    get "delete"
  end
  resources :schools do
    get "delete"
  end

  resources :subjects do
    get "delete"
  end

  resources :teachers do
    get "delete"
  end


  devise_for :users

  root to: 'static_pages#index'


  controller :students do
    get 'xls_index' => 'students#xls_creator'
    get 'students_of_group' => 'students#students_of_group'
  end

  controller :teachers do
    get 'teacher_index' => 'teachers#xls_creator'
  end

  controller :static_pages do 
    get '/index' => 'static_pages#index'

  end

end

app/models/student.rb
class Student < ActiveRecord::Base

	belongs_to :group
	belongs_to :school

	def self.create_student params
		student = Student.new student_params(params)

		school = School.find_by_name params[:student][:school]

		if school
			student.school = school
			student.save

		else
			student.errors.add(:school, "is not in the base")
		end
		student
	end


	private

		def self.student_params params
  			params.require(:student).permit(:first_name,:last_name,:email, :address, :phone_number, :group_id)
  		end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	respond_to :html, :js


  def students_of_group
    @group = Group.find_by_id(params[:format])
    @students = @group.students
  end

  def index
  	@students = Student.all.includes(:group).includes(:school)
  end


  def new
  	@group = Group.find(params[:format])
  	@student = Student.new
  end

  def create
  	@students = Student.all 
  	@student =  Student.create_student params

  	respond_to do |format|
       format.html { render :index }
       format.js
    end
  end

  

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @students = Student.all
    @student = Student.find(params[:id])
    @student.update_attributes(group_params)
    @student.save

    respond_to do |format|
       format.html { render :index }
       format.js
    end

  end

  def delete
    @student = Student.find(params[:student_id])
  end


  def destroy
      @students = Student.all
      @student = Student.find(params[:id])
      @student.destroy
  end

  def xls_creator
    package = Axlsx::Package.new
    workbook = package.workbook
    @students = Student.all
    workbook.add_worksheet(name: "Basic work sheet") do |sheet|
      sheet.add_row ["Student Name", "Address", "Phone", "Email", "School", "Group"]
      @students.each do |s|
         sheet.add_row ["#{s.first_name} #{s.last_name}", s.address, s.phone_number, s.email, s.school.name, s.group.name]
      end
    end
    package.serialize "Basic.xlsx"
    send_file("#{Rails.root}/Basic.xlsx", filename: "Basic.xlsx", type: "application/vnd.ms-excel")
  end

  private
  	
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_all_index.html.erb
<% @students.each do |student| %>
<tr >
	<td><%= "#{student.first_name} #{student.last_name}" %></td>
	<td><%= student.address %></td>
	<td><%= student.phone_number %></td>
	<td><%= student.email %></td>
	<td><%= student.school.name %></td>
	<td><%= student.group.name %></td>
	<td>
		<%= link_to("edit", edit_student_path(student) , remote: true, class: "btn btn-primary") %>
	</td>
	<td>
		<%= link_to("delete", student_delete_path(student), remote: true, class: "btn btn-danger") %>
	</td>
</tr>
<% end %>

app/views/students/_delete.js.erb
<div class="modal-header">
    <h3>Delete Sudent</h3>
    </div>
    <div class="modal-body">
    <ul class="errors"></ul>
    Are you sure you wish to delete?
    </div>
    <div class="modal-footer">
    <%= link_to "Yeah!!!", student_path(@student), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to "No!!", "#", class: "btn", data: { dismiss: "modal" } %>
    </div>

app/views/students/_form.html.erb
<%= form_for @student, remote: true, :authenticity_token => true, html: {class: "form-horizontal center", :id => 'student_form'} do |f| %>
   <div class="modal-body">
    <ul class="errors"></ul>
    <fieldset >
 
    <%= f.hidden_field :group_id, value: @group.id %>
   
    <div class="control-student">
      <%= f.label :first_name, class: "control-label" %>
      <div class="controls">
          <%= f.text_field :first_name%>
      </div>
    </div>

    <div class="control-student">
      <%= f.label :last_name, class: "control-label" %>
      <div class="controls">
          <%= f.text_field :last_name%>
      </div>
    </div>

    <div class="control-student">
      <%= f.label :address, class: "control-label" %>
      <div class="controls">
          <%= f.text_field :address%>
      </div>
    </div>

    <div class="control-student">
      <%= f.label :phone_number, class: "control-label" %>
      <div class="controls">
          <%= f.text_field :phone_number%>
      </div>
    </div>

    <div class="control-student">
      <%= f.label :email, class: "control-label" %>
      <div class="controls">
          <%= f.text_field :email%>
      </div>
    </div>

    <div class="control-student">
      <%= f.label :school, class: "control-label" %>
      <div class="controls">
          <%= f.text_field :school %>
      </div>
    </div>
    
   </div>
  <div class="modal-footer">
    <%= f.submit "Submit", class: "btn btn-large btn-primary" %>
    <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
  </div>
  </fieldset>
 
<% end %>

app/views/students/_index.html.erb
<% @students.each do |student| %>
<tr >
	<td><%= "#{student.first_name} #{student.last_name}" %></td>
	<td><%= student.address %></td>
	<td><%= student.phone_number %></td>
	<td><%= student.email %></td>
	<td>
		<%= link_to("edit", edit_student_path(student) , remote: true, class: "btn btn-primary") %>
	</td>
	<td>
		<%= link_to("delete", student_delete_path(student), remote: true, class: "btn btn-danger") %>
	</td>
</tr>
<% end %>

app/views/students/_new.html.erb
    <div class="modal-header">
    <h3>New Student</h3>
    </div>
    <%= render "form" %>

app/views/students/_save.js.erb
    $("ul.errors").html("")
    <% if @student.errors.any? %>
    <% @student.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
    <% end %>
    <% else %>
    $(".student-index").html("<%= escape_javascript(render 'index') %>")
    $("#student-modal").modal("hide")
    <% end %>

app/views/students/delete.js.erb
    $("#inner-student-modal").html("<%= escape_javascript(render 'delete') %>")
    $("#student-modal").modal("show")

app/views/students/index.html.erb
<%= link_to "Excel", xls_index_path %>
<div class="table-responsive">
<table class="table table-striped">
      <thead>
        <tr>
          <th>Student Name</th>
          <th>Address</th>
          <th>Phone</th>
          <th>Email</th>
          <th>Delete</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody class="student-index" >
      <%= render 'index' %>
      </tbody>
</table>

</div>
<div id="student-modal" class="modal fade">
  <div class="modal-dialog">
    <div id="inner-student-modal" class="modal-content"></div>
  </div>
</div>

app/views/students/new.js.erb
  $("#inner-student-modal").html("<%= escape_javascript(render 'new') %>")
   $("#student-modal").modal("show")

app/views/students/students_of_group.html.erb
<%= link_to("Add", new_student_path(@group), remote: true,  class: "btn btn-primary") %>
<div class="table-responsive">
<table class="table table-striped">
      <thead>
        <tr>
          <th>Student Name</th>
          <th>Address</th>
          <th>Phone</th>
          <th>Email</th>
          <th>Delete</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody class="student-index" >
      <%= render 'index' %>
      </tbody>
</table>

</div>
<div id="student-modal" class="modal fade">
  <div class="modal-dialog">
    <div id="inner-student-modal" class="modal-content"></div>
  </div>
</div>