config/routes.rb
Rails.application.routes.draw do
  
  resources :groups do
   get "delete"
  end
  resources :students do
    get "delete"
  end
  resources :schools do
    get "delete"
  end

  resources :subjects do
    get "delete"
  end

  resources :teachers do
    get "delete"
  end


  devise_for :users

  root to: 'static_pages#index'


  controller :students do
    get 'xls_index' => 'students#xls_creator'
    get 'students_of_group' => 'students#students_of_group'
  end

  controller :teachers do
    get 'teacher_index' => 'teachers#xls_creator'
  end

  controller :static_pages do 
    get '/index' => 'static_pages#index'

  end

end

app/models/group.rb
class Group < ActiveRecord::Base

	has_many :students

	validates :name, presence: true,
					 uniqueness: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  respond_to :html, :js

  def index
  	@groups = Group.all
  end

  def new
  	@group = Group.new
  end

  def create
  	@groups = Group.all 
  	@group =  Group.new(group_params)

  	@group.save

  	respond_to do |format|
       format.html { render :index }
       format.js
    end
  end

  

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @groups = Group.all
    @group = Group.find(params[:id])
    @group.update_attributes(group_params)
    @group.save

    respond_to do |format|
       format.html { render :index }
       format.js
    end

  end

  def delete
    @group = Group.find(params[:group_id])
  end


  def destroy
      @groups = Group.all
      @group = Group.find(params[:id])
      @group.destroy
  end


  private
  	def group_params
  		params.require(:group).permit(:name)
  	end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_delete.html.erb
<div class="modal-header">
    <h3>Delete Group</h3>
    </div>
    <div class="modal-body">
    <ul class="errors"></ul>
    Are you sure you wish to delete <b><%= @group.name %></b>?
    </div>
    <div class="modal-footer">
    <%= link_to "Yeah!!!", group_path(@group), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to "No!!", "#", class: "btn", data: { dismiss: "modal" } %>
    </div>

app/views/groups/_edit.html.erb
    <div class="modal-header">
    <h3><%= "Editing #{@group.name}" %></h3>
    </div>
    <%= render "form" %>

app/views/groups/_form.html.erb
<%= form_for @group, remote: true, :authenticity_token => true, html: {class: "form-horizontal center", :id => 'group_form'} do |f| %>
   <div class="modal-body">
    <ul class="errors"></ul>
    <fieldset >
 

   
    <div class="control-group">
      <%= f.label :name, class: "control-label" %>
      <div class="controls">
          <%= f.text_field :name%>
      </div>
    </div>


    
   </div>
  <div class="modal-footer">
    <%= f.submit "Submit", class: "btn btn-large btn-primary" %>
    <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
  </div>
  </fieldset>
 
<% end %>

app/views/groups/_index.html.erb
<% @groups.each do |group| %>
<tr >
	<td><%= group.name %></td>
	<td><%= group.students.count %></td>
	<td>
		<%= link_to("add students", students_of_group_path(group), class: "btn btn-primary") %>
	</td>
	<td>
		<%= link_to("edit", edit_group_path(group) , remote: true, class: "btn btn-primary") %>
	</td>
	<td>
		<%= link_to("delete", group_delete_path(group), remote: true, class: "btn btn-danger") %>
	</td>
</tr>
<% end %>

app/views/groups/_new.html.erb
    <div class="modal-header">
    <h3>New Group</h3>
    </div>
    <%= render "form" %>

app/views/groups/_save.js.erb
    $("ul.errors").html("")
    <% if @group.errors.any? %>
    <% @group.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
    <% end %>
    <% else %>
    $(".group-index").html("<%= escape_javascript(render 'index') %>")
    $("#group-modal").modal("hide")
    <% end %>

app/views/groups/delete.js.erb
    $("#inner-group-modal").html("<%= escape_javascript(render 'delete') %>")
    $("#group-modal").modal("show")

app/views/groups/edit.js.erb
    $("#inner-group-modal").html("<%= escape_javascript(render 'edit') %>")
    $("#group-modal").modal("show")

app/views/groups/index.html.erb
<h1> All groups </h1>


<%= link_to("Add", new_group_path, remote: true,  class: "btn btn-primary") %>
<div class="table-responsive">
<table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Num of students</th>
          <th>Add students</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody class="group-index" >
      <%= render 'index' %>
      </tbody>
</table>

</div>
<div id="group-modal" class="modal fade">
  <div class="modal-dialog">
    <div id="inner-group-modal" class="modal-content"></div>
  </div>
</div>

app/views/groups/new.js.erb
  $("#inner-group-modal").html("<%= escape_javascript(render 'new') %>")
   $("#group-modal").modal("show")