config/routes.rb
Rails.application.routes.draw do
  
  resources :groups do
   get "delete"
  end
  resources :students do
    get "delete"
  end
  resources :schools do
    get "delete"
  end

  resources :subjects do
    get "delete"
  end

  resources :teachers do
    get "delete"
  end


  devise_for :users

  root to: 'static_pages#index'


  controller :students do
    get 'xls_index' => 'students#xls_creator'
    get 'students_of_group' => 'students#students_of_group'
  end

  controller :teachers do
    get 'teacher_index' => 'teachers#xls_creator'
  end

  controller :static_pages do 
    get '/index' => 'static_pages#index'

  end

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	belongs_to :subject




	def self.find_by_filters filters
		teachers = if filters[:subject]
			self.joins(:subject).where("subject.name = ?", filters[:subject])
		else
			all
		end
	end


	def to_s
		"#{first_name} #{last_name}"
	end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
	
	def index
		@teachers = Teacher.all
	end

	def new
		@teacher = Teacher.new
		@subjects = Subject.all
	end

	def create
		@teachers = Teacher.all
		@teacher = Teacher.create teacher_params

		respond_to do |format|
       		format.html { render :index }
       		format.js
    	end
	end

	def edit
		@teacher = Teacher.find_by_id(params[:id])
		@subjects = Subject.all
	end

	def update
		 @teachers = Teacher.all
    	 @teacher = Teacher.find(params[:id])
    	 @teacher.update_attributes(teacher_params)
   		 @teacher.save

   		 respond_to do |format|
       		format.html { render :index }
       		format.js
    	 end
	end


	def delete
		@teacher = Teacher.find_by_id(params[:teacher_id])
	end

	def destroy
		@teachers = Teacher.all
      	@teacher = Teacher.find(params[:id])
     	@teacher.destroy
	end

	def find_by_filters
		@teachers = Teacher.find_by_filters params[:filters]

		render 'index'
	end

	def xls_creator
    package = Axlsx::Package.new
    workbook = package.workbook
    @teachers = Teacher.all.includes(:subject)
    workbook.add_worksheet(name: "Basic work sheet") do |sheet|
      sheet.add_row ["First Name", "Last Name", "Subject", "Email", "Phone"]
      @teachers.each do |t|
         sheet.add_row [t.first_name, t.last_name, t.subject.name, t.email, t.phone]
      end
    end
    package.serialize "Basic.xlsx"
    send_file("#{Rails.root}/Basic.xlsx", filename: "Basic.xlsx", type: "application/vnd.ms-excel")
  end


	private

		def teacher_params
			params.require(:teacher).permit(:first_name, :last_name, :email, :phone, :is_candidate, :subject_id)
		end

end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_delete.html.erb
<div class="modal-header">
    <h3>Delete Teacher</h3>
    </div>
    <div class="modal-body">
    <ul class="errors"></ul>
    Are you sure you wish to delete <b><%= @teacher.to_s %></b>?
    </div>
    <div class="modal-footer">
    <%= link_to "Yeah!!!", teacher_path(@teacher), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to "No!!", "#", class: "btn", data: { dismiss: "modal" } %>
    </div>

app/views/teachers/_edit.html.erb
    <div class="modal-header">
    <h3><%= "Editing #{@teacher.to_s }" %></h3>
    </div>
    <%= render "form" %>

app/views/teachers/_form.html.erb
<%= form_for @teacher, remote: true, :authenticity_token => true, html: {class: "form-horizontal center", :id => 'teacher_form'} do |f| %>
   <div class="modal-body">
    <ul class="errors"></ul>
    <fieldset >
 

   
    <div class="control-teacher">
      <%= f.label :first_name, class: "control-label" %>
      <div class="controls">
          <%= f.text_field :first_name%>
      </div>
    </div>

    <div class="control-teacher">
      <%= f.label :last_name, class: "control-label" %>
      <div class="controls">
          <%= f.text_field :last_name %>
      </div>
    </div>

     <div class="control-teacher">
      <%= f.label :email, class: "control-label" %>
      <div class="controls">
          <%= f.text_field :email %>
      </div>
    </div>

     <div class="control-teacher">
      <%= f.label :phone, class: "control-label" %>
      <div class="controls">
          <%= f.text_field :phone %>
      </div>
    </div>


    <div class="control-teacher">
      <%= f.label :is_candidate, class: "control-label" %>
      <div class="controls">
          <%= f.check_box :is_candidate %>
      </div>
    </div>

    <%= f.collection_select :subject_id, @subjects, :id, :name %>

   </div>
  <div class="modal-footer">
    <%= f.submit "Submit", class: "btn btn-large btn-primary" %>
    <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
  </div>
  </fieldset>
 
<% end %>

app/views/teachers/_index.html.erb
<% @teachers.each do |teacher| %>
<tr >
	<td><%= teacher.first_name %></td>
	<td><%= teacher.last_name %></td>
	<td><%= teacher.subject.name %></td>	
	<td><%= teacher.email %></td>
	<td><%= teacher.phone %></td>


	<td>
		<%= link_to("edit", edit_teacher_path(teacher) , remote: true, class: "btn btn-primary") %>
	</td>
	<td>
		<%= link_to("delete", teacher_delete_path(teacher), remote: true, class: "btn btn-danger") %>
	</td>
</tr>
<% end %>

app/views/teachers/_new.html.erb
    <div class="modal-header">
    <h3>New Teacher</h3>
    </div>
    <%= render "form" %>

app/views/teachers/_save.js.erb
    $("ul.errors").html("")
    <% if @teacher.errors.any? %>
    <% @teacher.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
    <% end %>
    <% else %>
    $(".teacher-index").html("<%= escape_javascript(render 'index') %>")
    $("#teacher-modal").modal("hide")
    <% end %>

app/views/teachers/create.js.erb
<%= render "save" %>

app/views/teachers/delete.js.erb
    $("#inner-teacher-modal").html("<%= escape_javascript(render 'delete') %>")
    $("#teacher-modal").modal("show")

app/views/teachers/destroy.js.erb
<%= render 'save' %>

app/views/teachers/edit.js.erb
    $("#inner-teacher-modal").html("<%= escape_javascript(render 'edit') %>")
    $("#teacher-modal").modal("show")

app/views/teachers/index.html.erb
<h1> All teachers </h1>


<%= link_to("Add", new_teacher_path, remote: true,  class: "btn btn-primary") %>
<%= link_to "Excel", teacher_index_path, class: "btn btn-primary" %>
<div class="table-responsive">
<table class="table table-striped">
      <thead>
        <tr>
          <th>First Nae</th>
          <th>Last Name</th>
          <th>Subject</th>
          <th>Email</th>
          <th>Phone</th>
        </tr>
      </thead>
      <tbody class="teacher-index" >
      <%= render 'index' %>
      </tbody>
</table>

</div>
<div id="teacher-modal" class="modal fade">
  <div class="modal-dialog">
    <div id="inner-teacher-modal" class="modal-content"></div>
  </div>
</div>

app/views/teachers/new.js.erb
  $("#inner-teacher-modal").html("<%= escape_javascript(render 'new') %>")
   $("#teacher-modal").modal("show")

app/views/teachers/update.js.erb
<%= render "save" %>