config/routes.rb
Rails.application.routes.draw do
  
  resources :groups do
   get "delete"
  end
  resources :students do
    get "delete"
  end
  resources :schools do
    get "delete"
  end

  resources :subjects do
    get "delete"
  end

  resources :teachers do
    get "delete"
  end


  devise_for :users

  root to: 'static_pages#index'


  controller :students do
    get 'xls_index' => 'students#xls_creator'
    get 'students_of_group' => 'students#students_of_group'
  end

  controller :teachers do
    get 'teacher_index' => 'teachers#xls_creator'
  end

  controller :static_pages do 
    get '/index' => 'static_pages#index'

  end

end

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Help</a></li>
            <li><a href="#">About</a></li>

            <% if user_signed_in? %>
              <li>
                <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
              </li>
              <li>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
              </li>
            <% else %>
              <li>
                <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %>
              </li>
              <li>
                <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
              </li>
            <% end %>
          </ul>
          
        </div>
      </div>
</div>

app/views/layouts/_sidebar.html.erb
       <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#">SideBar</a></li>
            <li>
             <%= link_to "Groups", groups_path %>
            </li>
            <li>
             <%= link_to "Students", students_path %>
            </li>
            <li>
              <%= link_to "Schools", schools_path %>
            </li>
            <li>
              <%= link_to "Subjects", subjects_path %>
            </li>
             <li>
              <%= link_to "Teachers", teachers_path %>
            </li>
          </ul>
         
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DiplomaApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= render 'layouts/header' %>




<div class="container-fluid">


  <div class="row" >
  <% if user_signed_in? %>
  	<%= render 'layouts/sidebar' %>
  <% end %>

  	<% if notice %>
  		<p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
  		<p class="alert alert-danger"><%= alert %></p>
	<% end %>

  	<%= yield %>
  
  </div>
</div>

</body>
</html>